### ISSUE TITLE
Did you get Daring Fireball type linked posts running on Astro yet?

### ISSUE THREAD

**Issue by twhite96** [scottaw66/scottwillsey2.0#1]
Cutting costs so I am making all my sites static and for ...tiff is typing, I want to have DF style linked posts in Astro but not sure how I'd go about that. Have you tried or do you have any resources to help out? It's the tiff from Mastodon by the way.

**Comment by scottaw66** [comment]
Oh, sorry. I don't look at GH much. No, I haven't yet. I have it in my to-do list. I'm not sure yet how I'm going to do it either.

**Comment by scottaw66** [comment]
I created a branch to work on this

**Comment by scottaw66** [comment]
@twhite96 Ok, I figured out how to do link posts. It's pretty easy. I just use an optional frontmatter value called "link" which contains the link to point to if it is a link post, and then check for its existence while building the post title.

I should have this up by tomorrow when I have time to finish it.

**Comment by scottaw66** [comment]
@twhite96 Support for link posts added. See src/components/PostTitle.astro, src/components/Post.astro, and src/content/posts/raycast.md for an example of how it works.

Basically I added an option "link" frontmatter variable to src/content/config.ts for posts, then in raycast.md I used this to link to https://www.theverge.com/23170431/raycast-how-to-macos-search-extensions-alfred-spotlight

Post.astro now calls PostTitle.astro to create the title, which in turn checks to see if post.data.link contains anything or not. If so, it links the title to that and shows a Link icon, otherwise it just creates a normal h1 title linked to the post itself.
